repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: Rust formatter
      - id: clippy
        name: Rust linter
        args:
          ["--fix", "--allow-dirty", "--all-targets", "--", "-D", "warnings"]
      - id: cargo-check
        name: Rust compiler check
